### ISSUE TITLE
Discussion: Add support for returning operation failure / cancelation reason

### ISSUE THREAD

**Issue by dxslly** [openid/OpenYOLO-Android#6]
### Background
OpenYolo for Android sends many of its requests via startActivityForResult. This allows for the for the credential provider to optionally display UI to the user without the need for additional handshakes.  The UI shown is not defined by the specification allowing each credential provider the freedom in what is displayed.

The specification does define responses for credentials retrieve, save and hint requests.  Each has a success case marked by a result code of RESULT_OK and a failure case marked by a result code of RESULT_CANCELED. 

### Proposal
Add support for more informative failure result codes that convey the users intent when a successful result is not returned.

### Motivation
A credential providers can return an unsuccessful response to a hint request, but the client is unsure if the user intends to continue or leave a sign up process.

**For example:** User Bob is using an shopping app, Bob begins the checkout process which requires the user to be signed in, the application is unable to find a credential via OpenYolo credential request and falls back to assisted sign up via a hint request, the credential provider may display a UI.  At this point the user may intend to leave the process by clicking the back button or a button on the credential provider's UI.  Clicking the back button may mark that the user wishes to exit the sign up process, while a custom button (For example: A credential picker is show, but Bob does not wish to use any of the available accounts, and clicks a "None of these accounts" button) may show intent to continue the sign up process and an absence of available credentials may not reveal any intent.

### Open Questions
- Is this important enough to justify changing the specification?  (With the rise of phone number only identifiers it may be common to run into the no credentials case)
- What possible intents would need to be accounted for? (I can currently think of the follow posibilities: UserCanceledBackwards, UserCancledForwards, ProviderCanceled)

**Comment by iainmcgin** [comment]
So, it will certainly be easy to carry extra information back to the app [via Intent data](https://goo.gl/sRwbDE) carried in the response. At a minimum, it may be worth defining some protocol buffers for carrying such information in a standard field of that Intent, even if those protocol buffer definitions are initially empty.

Beyond that, I was hesitant when defining the API initially to reveal more state about the user's credential provider than necessary. I don't have anything more than a vague uneasiness about that, however, and it would certainly seem valuable to be able to distinguish cancelation due to pressing the back button vs an explicit "none of the above" button press by the user.

**Comment by iainmcgin** [comment]
The proposed spec for the implementer's draft includes status codes, and we're in the process of implementing it here. Will open more specific issues to track each change.
