### ISSUE TITLE
Wire dependency require?

### ISSUE THREAD

**Issue by StanKocken** [openid/OpenYOLO-Android#61]
I don't know how you build the OpenYolo demo apps, but if I want to do it, I will have errors:

    error: package com.squareup.wire does not exist

To fix it, I have to import the library wire into my project BBQ:

    compile 'com.squareup.wire:wire-runtime:2.2.0'

Am I missing something? If not, why this dependency is not into the build.gradle and how is it working on your side?

**Comment by nerdyverde** [comment]
The protobuf library was changed from the Square implementation to Google’s implementation recently. If you’re updating your OpenYOLO prototype from a few weeks ago, you’ll likely have some minor refactoring to do to accommodate the changes. During the call the other day, Iain mentioned that he’s going to start pushing OpenYOLO to jcenter or maven so that we can more easily build against it.

Cheers,
Michael

**Comment by dxslly** [comment]
This error looks like it could be due to mixing modules from different commits. Recently there have been a number of breaking changes which could cause this.  I'd recommend ensuring you're using the latest version of the repo as a first step in trouble shooting.

**Comment by StanKocken** [comment]
Thanks guys.
I did update my repository to the latest version but some files were still present (containing wire).
I wiped the repository and clone it from scratch and now everything is working properly, the dependency is not require anymore.

**Comment by iainmcgin** [comment]
I'm part way there with pushing to jcenter; I pushed a provisional 0.1.0 release to bintray the other day which you can add as a dependency:

https://bintray.com/openid/net.openid/openyolo-spi

I'll sort out getting it into JCenter ASAP, as I also need it for my own purposes :)
